In [1]:
import pandas as pd
import openpyxl
import matplotlib as plt
import seaborn as sns

In [2]:
caminho = r"H:\Python\Terceira Etapa\Aula 4\CD2022_Populacao_2010_Compatibilizada_20231222 (1).xlsx"

df = pd.read_excel(
    caminho,
    sheet_name="Municípios",
    skiprows=2
)

df.head()

,Unnamed: 0,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010\n(Sinopse),População 2010 (Alterações de Limites até 2022)1,População Censo 2022
0,NaN,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,NaN,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,NaN,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,NaN,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,NaN,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0

In [3]:
df = df.iloc[:, 1:]

df.columns = [
    "UF",
    "COD. UF",
    "COD. MUNIC",
    "NOME DO MUNICÍPIO",
    "População Município 2010",
    "População 2010 Compatibilizada",
    "População Censo 2022"
]

df.head()

,UF,COD. UF,COD. MUNIC,NOME DO MUNICÍPIO,População Município 2010,População 2010 Compatibilizada,População Censo 2022
0,RO,11.0,15.0,Alta Floresta D'Oeste,24392.0,24392.0,21494.0
1,RO,11.0,23.0,Ariquemes,90353.0,90353.0,96833.0
2,RO,11.0,31.0,Cabixi,6313.0,6313.0,5351.0
3,RO,11.0,49.0,Cacoal,78574.0,78574.0,86887.0
4,RO,11.0,56.0,Cerejeiras,17029.0,17029.0,15890.0

In [4]:
col_2010 = "População 2010 Compatibilizada"
col_2022 = "População Censo 2022"

In [5]:
pop_estado = (
    df.groupby(["COD. UF", "UF"], as_index=False)
      .agg(
          populacao_2010=(col_2010, "sum"),
          populacao_2022=(col_2022, "sum"),
      )
)

pop_estado

    COD. UF  UF  populacao_2010  populacao_2022
0      11.0  RO       1562409.0       1581196.0
1      12.0  AC        733559.0        830018.0
2      13.0  AM       3483985.0       3941613.0
3      14.0  RR        450479.0        636707.0
4      15.0  PA       7581051.0       8120131.0
5      16.0  AP        669526.0        733759.0
6      17.0  TO       1383445.0       1511460.0
7      21.0  MA       6574789.0       6776699.0
8      22.0  PI       3119097.0       3271199.0
9      23.0  CE       8451644.0       8794957.0
10     24.0  RN       3168027.0       3302729.0
11     25.0  PB       3766528.0       3974687.0
12     26.0  PE       8796055.0       9058931.0
13     27.0  AL       3120887.0       3127683.0
14     28.0  SE       2067852.0       2210004.0
15     29.0  BA      14017071.0      14141626.0
16     31.0  MG      19597330.0      20539989.0
17     32.0  ES       3514952.0       3833712.0
18     33.0  RJ      15989929.0      16055174.0
19     35.0  SP      41262199.0      44411238.0
20     41.0  PR      10444526.0      11444380.0
21     42.0  SC       6248436.0       7610361.0
22     43.0  RS      10693929.0      10882965.0
23     50.0  MS       2449024.0       2757013.0
24     51.0  MT       3035122.0       3658649.0
25     52.0  GO       6001789.0       7056495.0
26     53.0  DF       2572159.0       2817381.0

In [6]:
pop_estado["crescimento"] = (
    pop_estado["populacao_2022"] -
    pop_estado["populacao_2010"]
)

In [7]:
pop_estado = pop_estado.sort_values(
    by="crescimento",
    ascending=False
)

pop_estado.head(10)

    COD. UF  UF  populacao_2010  populacao_2022  crescimento
19     35.0  SP      41262199.0      44411238.0    3149039.0
21     42.0  SC       6248436.0       7610361.0    1361925.0
25     52.0  GO       6001789.0       7056495.0    1054706.0
20     41.0  PR      10444526.0      11444380.0     999854.0
16     31.0  MG      19597330.0      20539989.0     942659.0
24     51.0  MT       3035122.0       3658649.0     623527.0
4      15.0  PA       7581051.0       8120131.0     539080.0
2      13.0  AM       3483985.0       3941613.0     457628.0
9      23.0  CE       8451644.0       8794957.0     343313.0
17     32.0  ES       3514952.0       3833712.0     318760.0

In [8]:
import os

os.makedirs("resultados", exist_ok=True)

In [9]:
pop_estado.to_csv(
    r"resultados\populacao_por_estado.csv",
    sep=";",
    index=False
)

In [10]:
pop_municipio = df[
    [
        "COD. UF",
        "UF",
        "COD. MUNIC",
        "NOME DO MUNICÍPIO",
        col_2010,
        col_2022
    ]
].copy()

In [11]:
pop_municipio = pop_municipio.rename(
    columns={
        col_2010: "populacao_2010",
        col_2022: "populacao_2022"
    }
)

pop_municipio.head()

,COD. UF,UF,COD. MUNIC,NOME DO MUNICÍPIO,populacao_2010,populacao_2022
0,11.0,RO,15.0,Alta Floresta D'Oeste,24392.0,21494.0
1,11.0,RO,23.0,Ariquemes,90353.0,96833.0
2,11.0,RO,31.0,Cabixi,6313.0,5351.0
3,11.0,RO,49.0,Cacoal,78574.0,86887.0
4,11.0,RO,56.0,Cerejeiras,17029.0,15890.0

In [12]:
pop_municipio["crescimento"] = (
    pop_municipio["populacao_2022"] -
    pop_municipio["populacao_2010"]
)

In [13]:
pop_municipio = pop_municipio.sort_values(
    by="crescimento",
    ascending=False
)

pop_municipio.head(10)

,COD. UF,UF,COD. MUNIC,NOME DO MUNICÍPIO,populacao_2010,populacao_2022,crescimento
111,13.0,AM,2603.0,Manaus,1802014.0,2063689.0,261675.0
5569,53.0,DF,108.0,Brasília,2572159.0,2817381.0,245222.0
3829,35.0,SP,50308.0,São Paulo,11253503.0,11451999.0,198496.0
3848,35.0,SP,52205.0,Sorocaba,586816.0,723682.0,136866.0
5417,52.0,GO,8707.0,Goiânia,1301912.0,1437366.0,135454.0
138,14.0,RR,100.0,Boa Vista,284313.0,413486.0,129173.0
4398,42.0,SC,5407.0,Florianópolis,421240.0,537211.0,115971.0
240,15.0,PA,5536.0,Parauapebas,153908.0,267836.0,113928.0
5122,50.0,MS,2704.0,Campo Grande,786774.0,898100.0,111326.0
1337,25.0,PB,7507.0,João Pessoa,723515.0,833932.0,110417.0

In [23]:
pop_municipio.to_csv(
    r"H:\Python\Terceira Etapa\Aula 4\resultados\populacao_por_municipio.csv",
    sep=";",
    index=False
)

In [24]:
pop_municipio = df[
    [
        "COD. UF",
        "UF",
        "COD. MUNIC",
        "NOME DO MUNICÍPIO",
        col_2010,
        col_2022
    ]
].copy()

In [25]:
pop_municipio = pop_municipio.rename(
    columns={
        col_2010: "populacao_2010",
        col_2022: "populacao_2022"
    }
)

pop_municipio.head()

,COD. UF,UF,COD. MUNIC,NOME DO MUNICÍPIO,populacao_2010,populacao_2022
0,11.0,RO,15.0,Alta Floresta D'Oeste,24392.0,21494.0
1,11.0,RO,23.0,Ariquemes,90353.0,96833.0
2,11.0,RO,31.0,Cabixi,6313.0,5351.0
3,11.0,RO,49.0,Cacoal,78574.0,86887.0
4,11.0,RO,56.0,Cerejeiras,17029.0,15890.0

In [26]:
pop_municipio["crescimento"] = (
    pop_municipio["populacao_2022"] -
    pop_municipio["populacao_2010"]
)

In [27]:
pop_municipio = pop_municipio.sort_values(
    by="crescimento",
    ascending=False
)

pop_municipio.head(10)

,COD. UF,UF,COD. MUNIC,NOME DO MUNICÍPIO,populacao_2010,populacao_2022,crescimento
111,13.0,AM,2603.0,Manaus,1802014.0,2063689.0,261675.0
5569,53.0,DF,108.0,Brasília,2572159.0,2817381.0,245222.0
3829,35.0,SP,50308.0,São Paulo,11253503.0,11451999.0,198496.0
3848,35.0,SP,52205.0,Sorocaba,586816.0,723682.0,136866.0
5417,52.0,GO,8707.0,Goiânia,1301912.0,1437366.0,135454.0
138,14.0,RR,100.0,Boa Vista,284313.0,413486.0,129173.0
4398,42.0,SC,5407.0,Florianópolis,421240.0,537211.0,115971.0
240,15.0,PA,5536.0,Parauapebas,153908.0,267836.0,113928.0
5122,50.0,MS,2704.0,Campo Grande,786774.0,898100.0,111326.0
1337,25.0,PB,7507.0,João Pessoa,723515.0,833932.0,110417.0

In [28]:
pop_municipio.to_csv(
    r"H:\Python\Terceira Etapa\Aula 4\resultados\populacao_por_municipio.csv",
    sep=";",
    index=False
)

In [29]:
top = pop_estado.head(10).copy()

In [30]:
top = top.melt(
    id_vars="UF",
    value_vars=["populacao_2010", "populacao_2022"],
    var_name="ano",
    value_name="populacao"
)

In [31]:
top["ano"] = top["ano"].replace({
    "populacao_2010": "2010",
    "populacao_2022": "2022"
})

In [32]:
fig, ax = plt.subplots(figsize=(10, 5))

sns.barplot(
    data=top,
    x="UF",
    y="populacao",
    hue="ano",
    ax=ax
)

ax.set_title(
    "10 UFs com maior crescimento absoluto: 2010 vs 2022"
)

ax.set_ylabel("Habitantes")
ax.set_xlabel("UF")

plt.xticks(rotation=30)
plt.tight_layout()
plt.show()

AttributeError: module 'matplotlib' has no attribute 'subplots'